# syntax=docker/dockerfile:1
FROM golang:1.18-buster AS builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./

RUN go mod download


COPY ./api/calculator_gw.go ./
COPY ./pb ./pb
RUN go build -o /calculator-gw
# Final Stage - Stage 2
FROM gcr.io/distroless/base-debian10 as baseImage
WORKDIR /app
COPY --from=builder /calculator-gw ./calculator-gw
COPY ./api/config ./config
COPY ./api/assembly.gotmpl ./
ENTRYPOINT ["/app/calculator-gw"]
EXPOSE 8002