# syntax=docker/dockerfile:1
FROM golang:1.18-buster AS builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./

RUN go mod download


COPY ./service/main.go ./
COPY ./pb ./pb
RUN go build -o /calculator
# Final Stage - Stage 2
FROM gcr.io/distroless/base-debian10 as baseImage
WORKDIR /app
COPY --from=builder /calculator ./calculator
COPY ./service/config ./config

ENTRYPOINT ["/app/calculator"]
EXPOSE 8001