apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime
  labels:
    app: prime
spec:
  selector:
    matchLabels:
      app: add
  replicas: 1
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
        - name: add
          image: shuzasa/add-service:v1.2
          ports:
            - name: add-service
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  selector:
    app: add
  ports:
    - port: 3000
      targetPort: add-service
