---
version: '2'
services:
  calculator:
    image: samutup/calculator:1.0.0
    hostname: calculator
    container_name: calculator
    ports:
      - "8001:8001"
  calculator-gw:
    image: samutup/calculator_gw:1.0.0
    hostname: calculator_gw
    container_name: calculator_gw
    ports:
      - "8002:8002"
    depends_on:
      - calculator

