apiVersion: v1
kind: Service
metadata:
  name: {{ include "prime.fullname" . }}
  labels:
    {{- include "prime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: prime
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8001
  selector:
    {{- include "prime.selectorLabels" . | nindent 4 }}
